# @summary This module manages prometheus nginx_vts_exporter
# @param arch
#  Architecture (amd64 or i386)
# @param bin_dir
#  Directory where binaries are located
# @param nginx_scrape_uri
#  The URI to obtain nginx JSON stats from
# @param download_extension
#  Extension for the release binary archive
# @param download_url
#  Complete URL corresponding to the where the release binary archive can be downloaded
# @param download_url_base
#  Base URL for the binary archive
# @param extra_groups
#  Extra groups to add the binary user to
# @param extra_options
#  Extra options added to the startup command
# @param group
#  Group under which the binary is running
# @param init_style
#  Service startup scripts style (e.g. rc, upstart or systemd)
# @param install_method
#  Installation method: url or package (only url is supported currently)
# @param manage_group
#  Whether to create a group for or rely on external code for that
# @param manage_service
#  Should puppet manage the service? (default true)
# @param manage_user
#  Whether to create user or rely on external code for that
# @param os
#  Operating system (linux is the only one supported)
# @param package_ensure
#  If package, then use this for package ensure default 'latest'
# @param package_name
#  The binary package name - not available yet
# @param purge_config_dir
#  Purge config files no longer generated by Puppet
# @param restart_on_change
#  Should puppet restart the service on configuration change? (default true)
# @param service_enable
#  Whether to enable the service from puppet (default true)
# @param service_ensure
#  State ensured for the service (default 'running')
# @param service_name
#  Name of the nginx-vts exporter service (default 'nginx-vts-exporter')
# @param user
#  User which runs the service
# @param version
#  The binary release version
class prometheus::nginxinc_exporter (


    # Installation options
  Enum['url','package'] $install_method   = 'url',
  Optional[Stdlib::HTTPUrl] $download_url = undef,
  Stdlib::HTTPUrl $download_url_base      = 'https://github.com/nginxinc/nginx-prometheus-exporter/releases',
  String $download_extension              = '',
  String[1] $version                      = '0.8.0',

  Package options (relevant when `install_method == 'package'`)
  String[1] $package_ensure               = 'installed',
  String[1] $package_name                 = 'nginxinc_exporter',

  # user/group configuration
  Boolean          $manage_user  = true,
  String[1]        $user         = 'nginxinc-exporter',
  Boolean          $manage_group = true,
  String[1]        $group        = 'nginxinc-exporter',
  Array[String[1]] $extra_groups = [],


  # service related options
  Boolean                         $manage_service = true,
  Optional[Prometheus::Initstyle] $init_style     = undef,
  String[1]                       $service_name   = 'nginxinc_exporter',
  Stdlib::Ensure::Service         $service_ensure = 'running',
  Boolean                         $service_enable = true,

    # exporter configuration
  Boolean $restart_on_change = true,

  String           $nginx_scrape_uri,

  Boolean          $purge_config_dir  = true,

  String           $init_style        = $facts['service_provider'],
  String           $install_method    = $prometheus::install_method,
  String           $os                = downcase($facts['kernel']),
  String           $extra_options     = '',
  String           $arch              = $prometheus::real_arch,
  String           $bin_dir           = $prometheus::bin_dir,
  Boolean $export_scrape_job          = false,
  Optional[Stdlib::Host] $scrape_host = undef,
  Stdlib::Port $scrape_port           = 9913,
  String[1] $scrape_job_name          = 'nginxinc',
  Optional[Hash] $scrape_job_labels   = undef,
) inherits prometheus {
  $real_download_url = pick($download_url,"${download_url_base}/download/v${version}/${package_name}-${version}.${os}-${arch}.${download_extension}")
  $notify_service = $restart_on_change ? {
    true    => Service[$service_name],
    default => undef,
  }

  $options = "-nginx.scrape_uri=\"${nginx_scrape_uri}\" ${extra_options}"

  prometheus::daemon { 'nginxinc-exporter':
    install_method     => $install_method,
    version            => $version,
    download_extension => $download_extension,
    os                 => $os,
    arch               => $arch,
    real_download_url  => $real_download_url,
    bin_dir            => $bin_dir,
    notify_service     => $notify_service,
    package_name       => $package_name,
    package_ensure     => $package_ensure,
    manage_user        => $manage_user,
    user               => $user,
    extra_groups       => $extra_groups,
    group              => $group,
    manage_group       => $manage_group,
    purge              => $purge_config_dir,
    options            => $options,
    init_style         => $init_style,
    service_ensure     => $service_ensure,
    service_enable     => $service_enable,
    manage_service     => $manage_service,
    export_scrape_job  => $export_scrape_job,
    scrape_host        => $scrape_host,
    scrape_port        => $scrape_port,
    scrape_job_name    => $scrape_job_name,
    scrape_job_labels  => $scrape_job_labels,
  }
}
